//Respuestas para todos los productos
export const ALL_PRODUCTS_REQUEST ="ALL_PRODUCTS_REQUEST"
export const ALL_PRODUCTS_SUCCESS="ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAIL="ALL_PRODUCTS_FAIL"

//Respuestas para producto detallado
export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL="PRODUCT_DETAILS_FAIL"

//Limpiar errores
export const CLEAR_ERRORS="CLEAR_ERRORS"